# M0X_labelled_data_sanity_check.R
# there are some tweets in the labelled data, which, upon being re-merged with the user-level information, such as ideology and location,
# appear to be missing. This shouldn't be the case, as there should be pertinent information attached to every single user, and thus, every
# single tweet. for this purpose, i pull in the data generated by "J_creating_samples_for_human_labelling.R"
# NL, 21/07/20

library(dplyr)
library(jsonlite)

UNLABELLED_DATA <- "Desktop/SENTIMENT/data/samples_for_labelling/"
LABELLED_DATA <- "Desktop/SENTIMENT/data/labelled_tweets/formatted/"

nh_unlabelled_df <- stream_in(con = file(paste0(UNLABELLED_DATA, "json/nh_tweet_sample.json")))
nh_unlabelled_csv_df <- read.csv(paste0(UNLABELLED_DATA, "nh_tweet_sample.csv"), colClasses = "character")
nh_labelled_df <- read.csv(paste0(LABELLED_DATA, "new_hampshire.csv"), colClasses = "character") %>% 
  mutate(id_str = external_id)

sc_unlabelled_df <- stream_in(con = file(paste0(UNLABELLED_DATA, "json/sc_tweet_sample.json")))
sc_unlabelled_csv_df <- read.csv(paste0(UNLABELLED_DATA, "sc_tweet_sample.csv"), colClasses = "character")
sc_labelled_df <- read.csv(paste0(LABELLED_DATA, "south_carolina.csv"), colClasses = "character") %>% 
  mutate(id_str = external_id)

ma_unlabelled_df <- stream_in(con = file(paste0(UNLABELLED_DATA, "json/ma_tweet_sample.json")))
ma_unlabelled_csv_df <- read.csv(paste0(UNLABELLED_DATA, "ma_tweet_sample.csv"), colClasses = "character")
ma_labelled_df <- read.csv(paste0(LABELLED_DATA, "massachussets.csv"), colClasses = "character") %>% 
  mutate(id_str = external_id)

nh_all_df <- left_join(nh_unlabelled_csv_df, nh_labelled_df, by = "id_str")

# -> figured out what the problem was. id_str in the original input data had some issue with, likely, multiple type conversions. 
# luckily, the original samples contain 
